question_data = {
    "response_code": 0,
    "results": [
        {
            "type": "boolean",
            "difficulty": "hard",
            "category": "Mythology",
            "question": "Janus was the Roman god of doorways and passageways.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Mythology",
            "question": "According to Norse mythology, Loki is a mother.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "hard",
            "category": "Mythology",
            "question": "Ska&eth;i is the Norse Goddess of skiing, mountains, winter and bowhunting.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Mythology",
            "question": "A wyvern is the same as a dragon.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Mythology",
            "question": "In Greek mythology, Hera is the goddess of harvest.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Mythology",
            "question": "In the Greek Mythology, the Gorgon can turn those who behold her to stone.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Mythology",
            "question": "According to Greek Mythology, Atlas was an Olympian God.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Mythology",
            "question": "According to Greek Mythology, Zeus can control lightning.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Mythology",
            "question": "The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Mythology",
            "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    ],
}
