# print("Hello World!\nHello World!\nHello World!\n")
# print("Hello"+" "+"Mike")
# print("Hello"+ " " + input("what is your name? ") + "!")
# name = input("what is your name? ")
# print(name)
# print(len(name))
# print(len(input("what is your name? ")))
# username = input("what is your name? ")
# length = len(username)
# print ("Hello " + username + "! Your name has " + str(length) + " characters.")

# band name generator ...
print("Welcome to the band name generator.")
city = input("what is the name of the city you grew up in?\n")
pet = input("what is your pet's name?\n")
print("Your band name could be: " + city + " " + pet)